window.CDL_SIMULATOR_QUESTIONS = [
  {
    id: "sim-001",
    topic: "Tanker",
    exam: "endorsements",
    difficulty: 2,
    section: "Section 8",
    question: "When a tank vehicle accelerates too sharply, what handling problem can the driver create?",
    choices: ["The moving liquid can surge and shift weight through the tank", "The fifth wheel automatically unlocks", "The low-air warning must turn on", "The placards become invalid"],
    answer: 0,
    explanation: "Sharp acceleration can make liquid surge. Tanker control depends on smooth acceleration, braking, and steering."
  },
  {
    id: "sim-002",
    topic: "Inspection",
    exam: "general",
    difficulty: 2,
    section: "Section 2.1",
    question: "During a walkaround, which finding should stop the trip until it is repaired?",
    choices: ["A steering component is loose or damaged", "The cab floor mat is dusty", "The trailer color does not match the tractor", "The radio preset was changed"],
    answer: 0,
    explanation: "Steering defects threaten control and must be corrected before operation."
  },
  {
    id: "sim-003",
    topic: "Air Brakes",
    exam: "air-brakes",
    difficulty: 2,
    section: "Section 5.3",
    question: "During an applied air-leak test on a two-vehicle combination, what are you checking?",
    choices: ["Pressure loss while holding the service brake down", "Whether the parking lights flash", "How fast the engine reaches idle", "The tread depth of the steering tires"],
    answer: 0,
    explanation: "The applied leakage test measures pressure drop while the brake pedal is held."
  },
  {
    id: "sim-004",
    topic: "Combination",
    exam: "combination",
    difficulty: 2,
    section: "Section 6.4",
    question: "After coupling a tractor-trailer, why is a visual fifth-wheel check still needed?",
    choices: ["A tug test alone may not prove the jaws are properly locked around the kingpin", "It replaces the need to connect air lines", "It lowers the trailer weight", "It checks fuel mileage"],
    answer: 0,
    explanation: "A safe coupling check includes both a tug test and a visual inspection of the connection."
  },
  {
    id: "sim-005",
    topic: "Speed",
    exam: "general",
    difficulty: 2,
    section: "Section 2.6",
    question: "A driver sees brake lights far ahead in traffic. What is the safest commercial-driver response?",
    choices: ["Ease off early and build stopping space before reaching the slowdown", "Keep speed until the last possible moment", "Move closer to prevent cars from entering the gap", "Turn on high beams"],
    answer: 0,
    explanation: "Commercial vehicles need early speed control because perception, reaction, and braking distance add up quickly."
  },
  {
    id: "sim-006",
    topic: "Cargo",
    exam: "cargo",
    difficulty: 2,
    section: "Section 3",
    question: "Why can a legal total weight still be unsafe?",
    choices: ["Weight may be poorly distributed across axles or too high in the vehicle", "Legal weight always means unsafe", "It cancels the inspection requirement", "It prevents cargo from shifting"],
    answer: 0,
    explanation: "Total weight, axle weight, height, and balance all affect steering, braking, and rollover risk."
  },
  {
    id: "sim-007",
    topic: "Night Driving",
    exam: "general",
    difficulty: 2,
    section: "Section 2.11",
    question: "At night, what should control your safe speed?",
    choices: ["The distance you can see and stop within", "The posted speed only", "The speed of smaller cars nearby", "The brightness of dashboard lights"],
    answer: 0,
    explanation: "You must be able to stop within the distance you can see."
  },
  {
    id: "sim-008",
    topic: "HazMat",
    exam: "endorsements",
    difficulty: 2,
    section: "Section 9",
    question: "Why must HazMat shipping papers be easy to identify and reach?",
    choices: ["Emergency responders need hazard information quickly", "They replace placards", "They make the truck lighter", "They allow texting while stopped"],
    answer: 0,
    explanation: "Shipping papers communicate critical hazard information during transport and emergencies."
  },
  {
    id: "sim-009",
    topic: "Backing",
    exam: "general",
    difficulty: 2,
    section: "Section 2.2",
    question: "A driver loses sight of the helper while backing. What should happen immediately?",
    choices: ["Stop until the helper is visible again", "Continue if the path looked clear before", "Speed up to finish sooner", "Use only the right mirror"],
    answer: 0,
    explanation: "If the helper disappears from view, stop. Backing must stay controlled and observable."
  },
  {
    id: "sim-010",
    topic: "Air Brakes",
    exam: "air-brakes",
    difficulty: 3,
    section: "Section 5.3",
    question: "What does it usually mean if air pressure builds too slowly during the build-rate test?",
    choices: ["The system may not recover air quickly enough for safe operation", "The cargo is too low", "The trailer doors are open", "The headlights are aimed too high"],
    answer: 0,
    explanation: "A slow build rate can indicate compressor or air-system problems."
  },
  {
    id: "sim-011",
    topic: "Space",
    exam: "general",
    difficulty: 2,
    section: "Section 2.7",
    question: "Why should you keep extra space ahead when driving a long combination vehicle?",
    choices: ["The vehicle needs more time and distance to stop or maneuver", "Extra space removes the need for mirrors", "It makes the trailer shorter", "It prevents all traffic from passing"],
    answer: 0,
    explanation: "Longer and heavier vehicles need more stopping and maneuvering room."
  },
  {
    id: "sim-012",
    topic: "Combination",
    exam: "combination",
    difficulty: 2,
    section: "Section 6.1",
    question: "Why should you avoid using the trailer hand valve as a normal braking method?",
    choices: ["It can cause trailer skids if used improperly", "It improves steering in every curve", "It drains fuel tanks", "It locks the steering axle"],
    answer: 0,
    explanation: "Improper use of the trailer hand valve can lock trailer wheels and cause a skid."
  },
  {
    id: "sim-013",
    topic: "Passenger",
    exam: "endorsements",
    difficulty: 2,
    section: "Section 4",
    question: "What is a key passenger-vehicle safety responsibility before moving?",
    choices: ["Make sure passengers and exits are safely managed", "Disable all emergency exits", "Let passengers stand in stairwells", "Ignore passenger count"],
    answer: 0,
    explanation: "Passenger safety includes loading, supervision, exits, and prohibited standing areas."
  },
  {
    id: "sim-014",
    topic: "Warning Devices",
    exam: "general",
    difficulty: 2,
    section: "Section 2.5",
    question: "What is the purpose of placing warning devices after a roadside stop?",
    choices: ["To warn approaching traffic before it reaches the vehicle", "To mark where cargo should be unloaded", "To replace hazard lights permanently", "To show where the driver parked earlier"],
    answer: 0,
    explanation: "Warning devices give approaching drivers time to react to a stopped CMV."
  },
  {
    id: "sim-015",
    topic: "School Bus",
    exam: "endorsements",
    difficulty: 2,
    section: "Section 10",
    question: "Why are danger zones central to school bus operation?",
    choices: ["Children can be close to the bus where the driver may not see them", "They only mark fuel-fill areas", "They are used only during rain", "They replace mirror checks"],
    answer: 0,
    explanation: "School bus drivers must constantly account for children around the bus, especially in blind spots."
  },
  {
    id: "sim-016",
    topic: "Mountain Driving",
    exam: "general",
    difficulty: 2,
    section: "Section 2.16",
    question: "What is the best time to select the gear for a steep downgrade?",
    choices: ["Before starting down the grade", "After the brakes begin smoking", "At the bottom of the hill", "Only after reaching highway speed"],
    answer: 0,
    explanation: "The proper gear and safe speed should be chosen before descending."
  },
  {
    id: "sim-017",
    topic: "Fires",
    exam: "general",
    difficulty: 2,
    section: "Section 2.21",
    question: "What should a driver do first when smoke or fire is suspected?",
    choices: ["Get the vehicle stopped safely and protect people", "Open the hood while driving", "Drive faster to blow smoke away", "Ignore it until the destination"],
    answer: 0,
    explanation: "Fire response starts with safe stopping, protecting people, and using proper emergency steps."
  },
  {
    id: "sim-018",
    topic: "Tanker",
    exam: "endorsements",
    difficulty: 2,
    section: "Section 8",
    question: "A baffled tank still requires careful driving because baffles do not fully control what?",
    choices: ["Side-to-side liquid movement", "Brake pressure warnings", "Placard requirements", "Tire tread depth"],
    answer: 0,
    explanation: "Baffles reduce forward/back surge, but side-to-side movement can still affect stability."
  },
  {
    id: "sim-019",
    topic: "Inspection",
    exam: "general",
    difficulty: 2,
    section: "Section 11",
    question: "In a vehicle inspection test, what makes an answer strong?",
    choices: ["Naming the part, its condition, and why the condition matters", "Only pointing silently", "Only naming the truck brand", "Skipping parts that look clean"],
    answer: 0,
    explanation: "The inspection test rewards component identification and safety explanation."
  },
  {
    id: "sim-020",
    topic: "Doubles/Triples",
    exam: "endorsements",
    difficulty: 2,
    section: "Section 7",
    question: "For doubles or triples, what valve pattern is safest at the rear of the last trailer?",
    choices: ["Air should pass through needed trailers and be closed at the end of the set", "Every valve should be closed before moving", "Every valve should be open at the very rear", "Valve position does not matter after coupling"],
    answer: 0,
    explanation: "Air must flow through the set, with shut-off valves closed at the back of the last trailer."
  },
  {
    id: "sim-021",
    topic: "Distracted Driving",
    exam: "general",
    difficulty: 1,
    section: "Section 2.9",
    question: "Why is texting especially risky in a CMV?",
    choices: ["It removes attention from a vehicle that needs extra time and space", "It improves reaction time", "It shortens stopping distance", "It is required by the handbook"],
    answer: 0,
    explanation: "CMVs require long visual lead time and full attention."
  },
  {
    id: "sim-022",
    topic: "Combination",
    exam: "combination",
    difficulty: 2,
    section: "Section 6.5",
    question: "Which item is specific to inspecting a tractor-trailer combination?",
    choices: ["Kingpin, fifth wheel, and locking jaws", "Passenger fare box", "Motorcycle chain", "School crossing arm only"],
    answer: 0,
    explanation: "Tractor-trailer inspection includes the coupling system."
  },
  {
    id: "sim-023",
    topic: "Cargo",
    exam: "cargo",
    difficulty: 2,
    section: "Section 3.3",
    question: "Why should cargo securement be rechecked after driving?",
    choices: ["Road vibration and braking can loosen or shift the load", "Cargo becomes legally weightless", "The shipper is no longer responsible for paperwork", "Tires stop needing inspection"],
    answer: 0,
    explanation: "Cargo can settle or shift during travel, so securement needs rechecking."
  },
  {
    id: "sim-024",
    topic: "ABS",
    exam: "general",
    difficulty: 2,
    section: "Section 2.18",
    question: "What should you remember about ABS?",
    choices: ["It helps preserve steering control but does not replace safe speed or space", "It lets you ignore slippery roads", "It removes the need for brakes", "It prevents every jackknife"],
    answer: 0,
    explanation: "ABS is a control aid, not a substitute for safe driving habits."
  },
  {
    id: "sim-025",
    topic: "Railroad Crossings",
    exam: "general",
    difficulty: 2,
    section: "Section 2.15",
    question: "If your vehicle stalls on railroad tracks, what should you prioritize?",
    choices: ["Leave the vehicle, move away from the tracks, and notify emergency help", "Stay in the cab and restart for several minutes", "Unload cargo on the tracks", "Wait for another driver to push you"],
    answer: 0,
    explanation: "Protect life first, then notify emergency responders or railroad contacts."
  },
  {
    id: "sim-026",
    topic: "Control",
    exam: "general",
    difficulty: 2,
    section: "Section 2.2",
    question: "What is the safest way to make a lane change in a CMV?",
    choices: ["Signal early, check mirrors, verify space, and move smoothly", "Signal after moving", "Turn sharply to finish quickly", "Use the horn instead of mirrors"],
    answer: 0,
    explanation: "Communication, observation, space, and smooth control work together."
  },
  {
    id: "sim-027",
    topic: "HazMat",
    exam: "endorsements",
    difficulty: 2,
    section: "Section 9",
    question: "What should a driver do if HazMat packages are leaking before departure?",
    choices: ["Do not transport them until the problem is handled according to rules", "Cover the leak with paper and leave", "Remove placards and continue", "Drive faster to reduce exposure time"],
    answer: 0,
    explanation: "Leaking HazMat creates serious safety and legal risks."
  },
  {
    id: "sim-028",
    topic: "Skids",
    exam: "general",
    difficulty: 2,
    section: "Section 2.19",
    question: "If locked wheels caused a skid, what must happen before steering control returns?",
    choices: ["The wheels must roll again and regain traction", "The mirrors must be folded", "The cargo must be unloaded", "The engine must be turned off immediately"],
    answer: 0,
    explanation: "Skid recovery depends on restoring traction."
  },
  {
    id: "sim-029",
    topic: "Air Brakes",
    exam: "air-brakes",
    difficulty: 2,
    section: "Section 5.1",
    question: "Why can repeated hard brake applications be risky in an air-brake vehicle?",
    choices: ["They can use air faster than the system recovers it", "They refill tanks instantly", "They improve brake adjustment automatically", "They remove the need for low-air warnings"],
    answer: 0,
    explanation: "Air brakes rely on stored air, and pressure must be maintained."
  },
  {
    id: "sim-030",
    topic: "General",
    exam: "general",
    difficulty: 2,
    section: "Section 1",
    question: "Why should a driver verify the license outcome before choosing a CDL school vehicle?",
    choices: ["The test vehicle can create restrictions that affect future jobs", "The vehicle color determines endorsements", "The school vehicle replaces written tests", "The road test score changes by brand"],
    answer: 0,
    explanation: "Transmission, air-brake, and combination setup can affect CDL restrictions."
  },
  {
    id: "sim-031",
    topic: "Hot Weather",
    exam: "general",
    difficulty: 2,
    section: "Section 2.14",
    question: "What heat-related vehicle issue deserves extra attention during hot weather?",
    choices: ["Tire condition and cooling-system temperature", "Trailer paint shine", "Dashboard brightness", "Seat fabric temperature only"],
    answer: 0,
    explanation: "Heat increases tire and engine cooling risks."
  },
  {
    id: "sim-032",
    topic: "Passenger",
    exam: "endorsements",
    difficulty: 2,
    section: "Section 4",
    question: "What should a passenger driver do before leaving a stop?",
    choices: ["Make sure doors are closed and passengers are safely positioned", "Start moving while people are still boarding", "Let passengers block the stairwell", "Ignore standing rules"],
    answer: 0,
    explanation: "Passenger safety depends on controlled loading, closed doors, and safe positioning."
  },
  {
    id: "sim-033",
    topic: "School Bus",
    exam: "endorsements",
    difficulty: 2,
    section: "Section 10",
    question: "Why is mirror adjustment critical before a school bus route?",
    choices: ["Mirrors help monitor danger zones around the bus", "Mirrors replace student-count procedures", "Mirrors remove the need to stop", "Mirrors are only decorative"],
    answer: 0,
    explanation: "School bus mirrors help drivers see areas where children may be hidden."
  },
  {
    id: "sim-034",
    topic: "Tanker",
    exam: "endorsements",
    difficulty: 2,
    section: "Section 8",
    question: "Why can a partly loaded smooth-bore tank be harder to control than a full tank?",
    choices: ["The liquid has more room to move and surge", "It has no need for outage", "It cannot roll over", "It disables the service brakes"],
    answer: 0,
    explanation: "Partial loads can surge strongly because liquid has room to move."
  },
  {
    id: "sim-035",
    topic: "Accidents",
    exam: "general",
    difficulty: 1,
    section: "Section 2.20",
    question: "After a crash, why should the driver protect the area?",
    choices: ["To reduce the chance of another crash", "To hide the vehicle", "To avoid using warning devices", "To move injured people quickly"],
    answer: 0,
    explanation: "Protecting the area prevents secondary collisions."
  },
  {
    id: "sim-036",
    topic: "Doubles/Triples",
    exam: "endorsements",
    difficulty: 2,
    section: "Section 7",
    question: "What makes converter dollies important to inspect carefully?",
    choices: ["They are coupling and braking links between trailers", "They steer the tractor front axle", "They replace warning triangles", "They are used only for decoration"],
    answer: 0,
    explanation: "A converter dolly is a critical connection in multi-trailer operation."
  },
  {
    id: "sim-037",
    topic: "Cargo",
    exam: "cargo",
    difficulty: 2,
    section: "Section 3.2",
    question: "What can happen if cargo is loaded too far to the rear?",
    choices: ["Steering and handling can be affected", "It always improves braking", "It removes rollover risk", "It cancels axle limits"],
    answer: 0,
    explanation: "Poor weight distribution can affect steering, braking, and legal axle weights."
  },
  {
    id: "sim-038",
    topic: "Fog",
    exam: "general",
    difficulty: 2,
    section: "Section 2.12",
    question: "What is dangerous about following another vehicle's taillights closely in fog?",
    choices: ["You may drive too fast for your own visibility and stopping distance", "It improves perception distance", "It guarantees the road is clear", "It replaces low beams"],
    answer: 0,
    explanation: "In fog, you need your own safe speed and space, not another driver's pace."
  },
  {
    id: "sim-039",
    topic: "Combination",
    exam: "combination",
    difficulty: 2,
    section: "Section 6.2",
    question: "What can happen if trailer air lines are crossed?",
    choices: ["Trailer brakes may not work as expected", "The headlights become brighter", "The cargo weight decreases", "The steering wheel locks"],
    answer: 0,
    explanation: "Air lines must be connected correctly for reliable trailer braking."
  },
  {
    id: "sim-040",
    topic: "General",
    exam: "general",
    difficulty: 2,
    section: "Section 1",
    question: "What is the best way to use a practice simulator before the real knowledge test?",
    choices: ["Use full tests to find weak topics, then review those handbook sections", "Memorize only answer positions", "Skip explanations after wrong answers", "Retake only the easiest questions"],
    answer: 0,
    explanation: "A simulator is most useful when misses drive targeted review."
  }
];
